### PR TITLE
Added newline between codeblock start and chunk

### PR DESCRIPTION
**Pull request by lizzyd710**
Fixed that thing that would sometimes hide the first word/line in the codeblock.

### CODE REVIEW

**Review by ada-phillips — APPROVED** [review]
Bless. Thank you for both noticing this problem and submitting the fix for it. I haven't had the time for any dev work lately. 
🛰

**Comment by lizzyd710** [comment]
No prob. Once it's merged I'll delete my fork because I too haven't had much time for dev work, but I'd be happy to look at any issues in the future when I'm less busy (and maybe have internet in my place of living.)

**Comment by lizzyd710** [comment]
I don't have write access, so I can't merge the changes, and I think that's the only step left.

**Comment by ada-phillips** [comment]
> 
> 
> I don't have write access, so I can't merge the changes, and I think that's the only step left.

I thought I changed the settings to allow anyone to write with an approval from me?

**Pull request merged**
